#!/bin/sh
#SBATCH --time=20-00:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=20
#SBATCH --constraint=IB
##SBATCH --mem=128000
#SBATCH --exclusive
##SBATCH --account=mdupuis2
#SBATCH --job-name=SPE-Fe2O3-Exp
#SBATCH --output=job.out
#SBATCH --mail-user=pasumart@buffalo.edu
#SBATCH --mail-type=END
#SBATCH --partition=mdupuis2
#SBATCH --clusters=chemistry
#SBATCH --error=job.err
#SBATCH --exclude=cpn-p28-42

export SCRATCH_DIR=$SLURM_SUBMIT_DIR
echo "SLURMTMPDIR is $SLURMTMPDIR"
export OMP_NUM_THREADS=1
export I_MPI_PIN=0
ulimit -s unlimited
export NNODES=`srun -l hostname | uniq | wc -l`
export NPROCS=`srun -l hostname | wc -l`

HOSTFILE=hosts.$SLURM_JOB_ID
srun hostname -s | sort > $HOSTFILE

cd $SLURM_SUBMIT_DIR
sbcast $SLURM_SUBMIT_DIR/KPOINTS $SLURMTMPDIR/KPOINTS
sbcast $SLURM_SUBMIT_DIR/POTCAR $SLURMTMPDIR/POTCAR
sbcast $SLURM_SUBMIT_DIR/POSCAR $SLURMTMPDIR/POSCAR
#sbcast $SLURM_SUBMIT_DIR/CHGCAR $SLURMTMPDIR/CHGCAR 
#sbcast $SLURM_SUBMIT_DIR/vdw_kernel.bindat $SLURMTMPDIR/vdw_kernel.bindat
sbcast $SLURM_SUBMIT_DIR/INCAR $SLURMTMPDIR/INCAR

cd $SLURMTMPDIR

source /etc/profile.d/modules.sh

module use /projects/academic/mdupuis2/software/modules/vasp
module load vasp5.4.1
module list
which vasp

echo "The number of nodes is $SLURM_NNODES"
echo "The number of processors per node $SLURM_NTASKS_PER_NODE"
echo "The number of processors is $NPROCS"

export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

SECONDS=0

srun --propagate=STACK vasp

cp $SLURMTMPDIR/* $SLURM_SUBMIT_DIR

/projects/academic/mdupuis2/vish/bin/vtstscripts-930/chgsum.pl AECCAR0 AECCAR2
/projects/academic/mdupuis2/vish/bin/bader CHGCAR_sum

duration=$SECONDS
days=$((duration/60/60/24))
hours=$((duration/60/60%24))
minutes=$((duration/60%60))
seconds=$((duration%60))
printf 'Time elapsed: '
(( $days > 0 )) && printf '%d days ' $days
(( $hours > 0 )) && printf '%d hours ' $hours
(( $minutes > 0 )) && printf '%d minutes ' $minutes
(( $days > 0 || $hours > 0 || $minutes > 0 )) && printf 'and '
printf '%d seconds\n' $seconds
