#!/bin/sh

#SBATCH --job-name=SPE-Fe2O3-Exp
#SBATCH --output=job.out
#SBATCH --error=job.err
#SBATCH --clusters=ub-hpc
#SBATCH --partition=general-compute
#SBATCH --qos=general-compute
#SBATCH --time=72:00:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=16
#SBATCH --exclusive
#SBATCH --mail-user=pasumart@buffalo.edu
#SBATCH --mail-type=END
#SBATCH --constraint=IB

# Job description:
# run vasp job followed by bader analysis; also prints the job run time to the output file

echo "SLURMTMPDIR is $SLURMTMPDIR"
export OMP_NUM_THREADS=1
export I_MPI_PIN=0
ulimit -s unlimited
export NNODES=`srun -l hostname | uniq | wc -l`
export NPROCS=`srun -l hostname | wc -l`

HOSTFILE=hosts.$SLURM_JOB_ID
srun hostname -s | sort > $HOSTFILE

cd $SLURM_SUBMIT_DIR
sbcast $SLURM_SUBMIT_DIR/KPOINTS $SLURMTMPDIR/KPOINTS
sbcast $SLURM_SUBMIT_DIR/POTCAR $SLURMTMPDIR/POTCAR
sbcast $SLURM_SUBMIT_DIR/POSCAR $SLURMTMPDIR/POSCAR
sbcast $SLURM_SUBMIT_DIR/INCAR $SLURMTMPDIR/INCAR
cd $SLURMTMPDIR

module use /projects/academic/mdupuis2/software/modules/vasp5.4.4
module load vasp5.4.4
module list
which vasp

echo "The number of nodes is $SLURM_NNODES"
echo "The number of processors per node $SLURM_NTASKS_PER_NODE"
echo "The number of processors is $NPROCS"

TimeLimit=`sacct -j ${SLURM_JOB_ID} -o TimeLimit -n`
TimeLimit=`printf "%s" "${TimeLimit:0:10}"`
TimeLimitSubString=${TimeLimit:0:4}
TimeLimitDays=${TimeLimit:0:1}
if [ $TimeLimitDays ]; then
    TimeLimitHr=$(($TimeLimitDays * 24 + ${TimeLimit:2:2}))
else
    TimeLimitHr=${TimeLimit:2:2}
fi

printf "TimeLimitHr: %d\n" $TimeLimitHr

export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

SECONDS=0

srun --propagate=STACK vasp

/projects/academic/mdupuis2/vish/lib/vtstscripts-930/chgsum.pl AECCAR0 AECCAR2
/projects/academic/mdupuis2/vish/lib/vtstscripts-930/chgsplit.pl CHGCAR
/projects/academic/mdupuis2/vish/bin/bader CHGCAR -ref CHGCAR_sum
#/projects/academic/mdupuis2/vish/bin/bader CHGCAR_mag -ref CHGCAR_sum

cp $SLURMTMPDIR/* $SLURM_SUBMIT_DIR

duration=$SECONDS
days=$((duration/60/60/24))
hours=$((duration/60/60%24))
minutes=$((duration/60%60))
seconds=$((duration%60))
printf 'Time elapsed: '
(( $days > 0 )) && printf '%d days ' $days
(( $hours > 0 )) && printf '%d hours ' $hours
(( $minutes > 0 )) && printf '%d minutes ' $minutes
(( $days > 0 || $hours > 0 || $minutes > 0 )) && printf 'and '
printf '%d seconds\n' $seconds
